"""Hypothesis strategies for PBT initial conditions (spec § 2.14).

The strategies here return plain NumPy arrays or dictionaries; the sim
runner consumes them. Each strategy declares its applicable Tier-2
substack via the docstring; Phase-1+ sims extend this library as needed.
"""

from __future__ import annotations

import numpy as np
from hypothesis import strategies as st
from hypothesis.extra.numpy import arrays
from hypothesis.strategies import SearchStrategy


def smooth_scalar_field_in_unit_box(
    shape: tuple[int, ...] = (32,),
    lo: float = 0.0,
    hi: float = 1.0,
) -> SearchStrategy[np.ndarray]:
    """Random smooth-ish scalar field on a uniform grid; values in [lo, hi].

    "Smooth-ish" here means the field is generated by sampling K low-frequency
    Fourier coefficients (drawn from a bounded Hypothesis strategy) and
    summing the resulting real-valued field. K is intentionally small so the
    field is genuinely smooth at the sample resolution. For Phase 0 we use
    K = 4 and bound the coefficient magnitudes so the resulting field stays
    inside [lo, hi] without clipping.

    Applicable to: continuous-CA Tier-2 substacks.
    """
    k_max = 4

    @st.composite
    def _strategy(draw: st.DrawFn) -> np.ndarray:
        coeffs = draw(
            arrays(
                dtype=np.float64,
                shape=(k_max,),
                elements=st.floats(min_value=-0.1, max_value=0.1, allow_nan=False),
            )
        )
        n = shape[0]
        x = (np.arange(n) + 0.5) / n
        field = np.full(n, (lo + hi) * 0.5, dtype=np.float64)
        for k_index, c in enumerate(coeffs, start=1):
            field = field + c * np.sin(2.0 * np.pi * k_index * x)
        field = np.clip(field, lo, hi)
        return field.astype(np.float64)

    return _strategy()


def random_particle_configuration_1d(
    n_particles: int = 8,
    domain: tuple[float, float] = (0.0, 1.0),
) -> SearchStrategy[np.ndarray]:
    """Random 1D particle positions in `(N, 1)` shape; bounded by `domain`.

    Applicable to: particle-fluid Tier-2 substack (SPH-like). Positions are
    drawn IID uniformly within the domain; the Hypothesis shrinker drives
    counter-examples toward boundary or coincident configurations.
    """
    lo, hi = domain
    return arrays(
        dtype=np.float64,
        shape=(n_particles, 1),
        elements=st.floats(min_value=lo, max_value=hi, allow_nan=False),
    )


def random_seed() -> SearchStrategy[int]:
    """Arbitrary nonnegative seed (clamped well below 2**31)."""
    return st.integers(min_value=0, max_value=(1 << 30) - 1)
