"""f64 NumPy reference — D2Q9 pseudopotential multiphase LBM (NORMATIVE).

The gate kernel contract shared with the WGSL implementation
(`packages/lbm-multiphase/web/src/lbm_core.wgsl`), spec
`docs/sim-specs/lattice/lbm-multiphase/spec-ref.md` §§ 3, 6:

1. **DDF-shifted state** ``fbar_i = f_i - w_i`` (Skordos/Lehmann shift, spec
   § 3.5/§ 9 guard 1) — the f32 conditioning contract. rho = 1 + sum fbar.
2. **Two-buffer pull streaming**, halfway bounce-back at solid cells
   (bounce-back is shift-invariant because w_i = w_opp(i)).
3. **Pinned operation order** in equilibrium/forcing (see `collide_stream`);
   all reductions over i are SEQUENTIAL i = 0..8 accumulation, never pairwise
   summation — the WGSL loop is the same order.
4. **No runtime transcendentals on the gate path**: Tier-A psi comes from the
   committed f64 LUT (`psi_lut`, linear interp, pinned arithmetic); Tier-B
   psi is polynomial + sqrt + division. Scene ICs are committed f64 fields.
5. All steppers are dtype-preserving: the same code runs the f64 gates AND
   the f32 WGSL-proxy tolerance measurement (heat-equation/fdtd pattern).

Convention: Krüger lattice-weight form (spec § 3.3) —
F = -G psi(x) sum_i w_i psi(x+c_i) c_i, bulk EOS p = rho cs^2 + G cs^2/2 psi^2.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final, Literal

import numpy as np

# --------------------------------------------------------------------------
# D2Q9 constants (velocity order NORMATIVE: rest; +x,+y,-x,-y; then
# (+1,+1),(-1,+1),(-1,-1),(+1,-1) — pinned in the derivation doc
# tools/testkit/golden/derivations/d2q9.md and mirrored by the WGSL kernel)
# --------------------------------------------------------------------------
CX: Final = np.array([0, 1, 0, -1, 0, 1, -1, -1, 1], dtype=np.int64)
CY: Final = np.array([0, 0, 1, 0, -1, 1, 1, -1, -1], dtype=np.int64)
W: Final = np.array(
    [4 / 9, 1 / 9, 1 / 9, 1 / 9, 1 / 9, 1 / 36, 1 / 36, 1 / 36, 1 / 36],
    dtype=np.float64,
)
OPP: Final = np.array([0, 3, 4, 1, 2, 7, 8, 5, 6], dtype=np.int64)
CS2: Final[float] = 1.0 / 3.0

# Tier-A psi LUT (committed data spine): psi0 exp(-rho0/rho), psi0 = rho0 = 1,
# uniform grid over [0, PSI_LUT_RHO_MAX], PSI_LUT_N entries, psi(0) = 0.
PSI_LUT_N: Final[int] = 8192
PSI_LUT_RHO_MAX: Final[float] = 6.0

# sigma-forcing vapor-phase regularization (spec § 9 guard 2): psi^2 in the
# v' denominator is clamped at EPS_PSI2. Measured basis: the smallest gated
# psi^2 (C-S vapor at T/Tc = 0.8) is ~1.4e-2 — six orders above the clamp —
# so the clamp NEVER fires on gated scenes (asserted in tests) and exists
# only to keep interactive abuse (user-driven near-vacuum) finite.
EPS_PSI2: Final[float] = 1e-8


def build_psi_lut() -> np.ndarray:
    """The committed Tier-A psi table (f64). Generated by CPython once and
    committed as `web/public/lbm-psi-lut-f64.bin`; the browser casts it to
    f32. Element 0 is psi(0) = lim_{rho->0} exp(-1/rho) = 0."""
    rho = np.linspace(0.0, PSI_LUT_RHO_MAX, PSI_LUT_N)
    with np.errstate(divide="ignore"):
        out = np.exp(-1.0 / np.maximum(rho, 1e-300))
    out[0] = 0.0
    return out


def psi_from_lut(rho: np.ndarray, lut: np.ndarray) -> np.ndarray:
    """Pinned LUT interpolation (identical arithmetic in WGSL):

    t = rho * ((N-1)/rho_max); i = floor(t) clamped to [0, N-2];
    psi = lut[i] + (t - i) * (lut[i+1] - lut[i])
    """
    dt = rho.dtype.type
    scale = dt((PSI_LUT_N - 1) / PSI_LUT_RHO_MAX)
    t = rho * scale
    idx = np.clip(t.astype(np.int64), 0, PSI_LUT_N - 2)
    frac = t - idx.astype(rho.dtype)
    lo = lut[idx]
    return (lo + frac * (lut[idx + 1] - lo)).astype(rho.dtype)


def psi_cs_field(rho: np.ndarray, temp: float, g: float) -> np.ndarray:
    """Tier-B Yuan-Schaefer psi for the C-S EOS, dtype-preserving, pinned
    order (polynomial + sqrt + division only — WGSL-safe). The sqrt argument
    is clamped at 0 for interactive robustness; gated scenes assert the
    clamp never fires (`psi_cs_arg_min`)."""
    dt = rho.dtype.type
    phi = rho * dt(0.25 * 4.0)  # b/4 with b=4 — written as one constant
    one = dt(1.0)
    num = one + phi * (one + phi * (one - phi))  # 1 + phi + phi^2 - phi^3
    den = one - phi
    p_eos = rho * dt(1.0) * dt(temp) * num / (den * den * den) - dt(1.0) * rho * rho
    arg = dt(2.0) * (p_eos - rho * dt(CS2)) / dt(g * CS2)
    return np.sqrt(np.maximum(arg, dt(0.0)))


def psi_cs_arg_min(rho: np.ndarray, temp: float, g: float) -> float:
    """Minimum sqrt argument over the field — gated scenes assert > 0."""
    r = rho.astype(np.float64)
    phi = r
    num = 1.0 + phi * (1.0 + phi * (1.0 - phi))
    den = 1.0 - phi
    p_eos = r * temp * num / (den**3) - r * r
    return float((2.0 * (p_eos - r * CS2) / (g * CS2)).min())


# --------------------------------------------------------------------------
# Scene description
# --------------------------------------------------------------------------

Forcing = Literal["guo", "li-sigma", "sc-shift"]
PsiKind = Literal["exp-lut", "cs"]


@dataclass(frozen=True)
class MultiphaseScene:
    """A pinned pseudopotential scene (gate scenes are Final instances).

    ``rho_ic`` is the committed f64 initial density field (nx, ny); the
    initial state is fbar_i = w_i (rho - 1) (equilibrium at rest — exact in
    every dtype because it is a single multiply)."""

    name: str
    nx: int
    ny: int
    psi_kind: PsiKind
    g: float
    tau: float
    forcing: Forcing
    steps: int
    checkpoints: tuple[int, ...]
    sigma: float = 0.0  # li-sigma only
    cs_temp: float = 0.0  # psi_kind == "cs" only
    gravity: tuple[float, float] = (0.0, 0.0)  # buoyancy form (rho - rho_ref) g
    rho_ref: float = 1.0  # fixed buoyancy reference (IC mean; NOT per-step)
    solid: np.ndarray | None = None  # bool (nx, ny)
    rho_wall: float = 0.0  # virtual wall density for wetting (psi at solids)
    rho_ic: np.ndarray = field(default_factory=lambda: np.zeros((0, 0)))


@dataclass
class SceneResult:
    checkpoints: dict[int, tuple[np.ndarray, np.ndarray, np.ndarray]]
    final_fbar: np.ndarray  # (9, nx, ny) post-collision state at scene.steps
    psi_min_arg: float  # min C-S sqrt arg seen (Tier B honesty assert)


def run_scene(scene: MultiphaseScene, dtype: type = np.float64) -> SceneResult:
    """Run the scene; return {step: (rho, ux, uy)} at checkpoints (physical
    velocity, solid cells zeroed) plus the final post-collision state.

    NORMATIVE per-step order (the contract; do not reorder):
      stream (pull + halfway bounce-back) -> macro (rho, momentum) ->
      psi field (solids carry psi(rho_wall)) -> interaction force + gravity
      -> velocity closure per forcing scheme -> collide + source -> write.
    """
    dt = np.dtype(dtype).type
    nx, ny = scene.nx, scene.ny
    if scene.rho_ic.shape != (nx, ny):
        raise ValueError("scene.rho_ic shape mismatch")
    lut = build_psi_lut().astype(dtype)
    solid = scene.solid if scene.solid is not None else np.zeros((nx, ny), dtype=bool)
    fluid = ~solid
    w = W.astype(dtype)
    tau = dt(scene.tau)
    inv_tau = dt(1.0) / tau
    half = dt(0.5)
    g_coup = dt(scene.g)
    src_pref = dt(1.0) - half * inv_tau  # (1 - 1/(2 tau))
    gx, gy = dt(scene.gravity[0]), dt(scene.gravity[1])
    has_gravity = scene.gravity != (0.0, 0.0)

    rho0 = scene.rho_ic.astype(dtype)
    fbar = np.stack([w[i] * (rho0 - dt(1.0)) for i in range(9)])
    fbar[:, solid] = dt(0.0)

    if scene.psi_kind == "exp-lut":
        psi_wall = dt(
            float(psi_from_lut(np.array([scene.rho_wall]), build_psi_lut())[0])
        )
    else:
        psi_wall = dt(
            float(
                psi_cs_field(
                    np.array([scene.rho_wall], dtype=np.float64),
                    scene.cs_temp,
                    scene.g,
                )[0]
            )
        )

    caps: dict[int, tuple[np.ndarray, np.ndarray, np.ndarray]] = {}
    min_arg = np.inf
    f_pre = np.empty_like(fbar)

    for t in range(1, scene.steps + 1):
        # ---- stream (pull) + halfway bounce-back --------------------------
        for i in range(9):
            pulled = np.roll(fbar[i], (int(CX[i]), int(CY[i])), axis=(0, 1))
            from_solid = np.roll(solid, (int(CX[i]), int(CY[i])), axis=(0, 1))
            f_pre[i] = np.where(from_solid, fbar[OPP[i]], pulled)
        f_pre[:, solid] = dt(0.0)

        # ---- macroscopics (sequential i-order accumulation) ---------------
        rho = np.full((nx, ny), dt(1.0))
        mx = np.zeros((nx, ny), dtype)
        my = np.zeros((nx, ny), dtype)
        for i in range(9):
            rho = rho + f_pre[i]
            if CX[i]:
                mx = mx + dt(float(CX[i])) * f_pre[i]
            if CY[i]:
                my = my + dt(float(CY[i])) * f_pre[i]

        # ---- psi field -----------------------------------------------------
        if scene.psi_kind == "exp-lut":
            psi = psi_from_lut(rho, lut)
        else:
            psi = psi_cs_field(rho, scene.cs_temp, scene.g)
            if fluid.any():
                a = psi_cs_arg_min(rho[fluid], scene.cs_temp, scene.g)
                min_arg = min(min_arg, a)
        psi = np.where(solid, psi_wall, psi)

        # ---- interaction force (Kruger convention) ------------------------
        sx = np.zeros((nx, ny), dtype)
        sy = np.zeros((nx, ny), dtype)
        for i in range(1, 9):
            nb = np.roll(psi, (-int(CX[i]), -int(CY[i])), axis=(0, 1))
            wnb = w[i] * nb
            sx = sx + wnb * dt(float(CX[i]))
            sy = sy + wnb * dt(float(CY[i]))
        fx = -g_coup * psi * sx
        fy = -g_coup * psi * sy
        if has_gravity:
            rho_ref = dt(scene.rho_ref)
            fx = fx + (rho - rho_ref) * gx
            fy = fy + (rho - rho_ref) * gy

        # ---- velocity closure ----------------------------------------------
        inv_rho = dt(1.0) / rho
        if scene.forcing == "sc-shift":
            # pedagogy/negative-control scheme: eq velocity shifted by tau F
            vx = (mx + tau * fx) * inv_rho
            vy = (my + tau * fy) * inv_rho
            out_vx = (mx + half * fx) * inv_rho
            out_vy = (my + half * fy) * inv_rho
        else:
            vx = (mx + half * fx) * inv_rho
            vy = (my + half * fy) * inv_rho
            out_vx, out_vy = vx, vy
        if scene.forcing == "li-sigma":
            denom = (tau - half) * np.maximum(psi * psi, dt(EPS_PSI2))
            corr = dt(scene.sigma) / denom
            vpx = vx + corr * fx
            vpy = vy + corr * fy
        else:
            vpx, vpy = vx, vy

        # ---- collide + source (pinned equilibrium order) -------------------
        u2 = vx * vx + vy * vy
        rho_m1 = rho - dt(1.0)
        for i in range(9):
            cxi, cyi = dt(float(CX[i])), dt(float(CY[i]))
            cu = dt(3.0) * (cxi * vx + cyi * vy)
            feq = w[i] * (rho_m1 + rho * (cu + half * cu * cu - dt(1.5) * u2))
            fstar = f_pre[i] - inv_tau * (f_pre[i] - feq)
            if scene.forcing != "sc-shift":
                cf = dt(3.0) * ((cxi - vpx) * fx + (cyi - vpy) * fy)
                cvp = cxi * vpx + cyi * vpy
                cf = cf + dt(9.0) * cvp * (cxi * fx + cyi * fy)
                fstar = fstar + src_pref * w[i] * cf
            fbar[i] = fstar
        fbar[:, solid] = dt(0.0)

        if t in scene.checkpoints:
            r_out = np.where(solid, dt(0.0), rho)
            vx_out = np.where(solid, dt(0.0), out_vx)
            vy_out = np.where(solid, dt(0.0), out_vy)
            caps[t] = (r_out.copy(), vx_out.copy(), vy_out.copy())

    return SceneResult(
        checkpoints=caps,
        final_fbar=fbar.copy(),
        psi_min_arg=float(min_arg),
    )


# --------------------------------------------------------------------------
# Scene builders (ICs are analytic in f64 here, then COMMITTED as .bin —
# the browser never recomputes tanh)
# --------------------------------------------------------------------------


def flat_interface_ic(
    nx: int, ny: int, rho_v: float, rho_l: float, x0: float, x1: float, width: float
) -> np.ndarray:
    """Liquid slab x in [x0, x1] between vapor, tanh-smoothed (f64)."""
    x = np.arange(nx, dtype=np.float64)[:, None]
    prof = 0.5 * (np.tanh((x - x0) / width) - np.tanh((x - x1) / width))
    rho = rho_v + (rho_l - rho_v) * prof
    return np.repeat(rho, ny, axis=1)


def droplet_ic(
    nx: int,
    ny: int,
    rho_out: float,
    rho_in: float,
    cx: float,
    cy: float,
    rx: float,
    ry: float,
    width: float,
    seed_eps: float = 0.0,
) -> np.ndarray:
    """Elliptical droplet (rx = ry for circles), tanh interface; optional
    deterministic seeded asymmetry (spec § 9 guard 3) via a fixed harmonic."""
    x = np.arange(nx, dtype=np.float64)[:, None]
    y = np.arange(ny, dtype=np.float64)[None, :]
    r = np.sqrt(((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2) * min(rx, ry)
    rho = rho_out + (rho_in - rho_out) * 0.5 * (
        1.0 - np.tanh((r - min(rx, ry)) / width)
    )
    if seed_eps:
        rho = rho * (
            1.0 + seed_eps * np.sin(2.0 * np.pi * x / nx) * np.cos(2.0 * np.pi * y / ny)
        )
    return rho


def bulk_pressure_field(rho: np.ndarray, psi: np.ndarray, g: float) -> np.ndarray:
    """p = rho cs^2 + (G cs^2/2) psi^2 — evaluated on measured fields."""
    return rho * CS2 + 0.5 * g * CS2 * psi * psi


__all__ = [
    "CS2",
    "CX",
    "CY",
    "EPS_PSI2",
    "OPP",
    "PSI_LUT_N",
    "PSI_LUT_RHO_MAX",
    "W",
    "MultiphaseScene",
    "SceneResult",
    "build_psi_lut",
    "bulk_pressure_field",
    "droplet_ic",
    "flat_interface_ic",
    "psi_cs_arg_min",
    "psi_cs_field",
    "psi_from_lut",
    "run_scene",
]
