"""Convergence analyzer for the MMS pipeline.

Given a `RunnerResult`, compute per-resolution L2 and L-infinity errors against
the manufactured solution, fit observed order via least-squares in log-log
space, and return a verdict against the scheme's formal order.

Pass criterion (spec § 2.2): the observed order is within +/- 0.5 of the
formal spatial order. The default tolerance is documented in `acceptance.md`
and matches Block 2's prompt.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final

import numpy as np
from numpy.typing import NDArray

from .runner import PerResolutionResult, RunnerResult

DEFAULT_ORDER_TOLERANCE: Final[float] = 0.5


@dataclass(frozen=True)
class PerResolutionError:
    """L2 / L-inf error for a single resolution."""

    N: int
    dx: float
    l2_error: float
    linf_error: float


@dataclass(frozen=True)
class ConvergenceResult:
    """Result of an MMS convergence analysis."""

    per_resolution: tuple[PerResolutionError, ...]
    formal_order: float
    observed_order_l2: float
    observed_order_linf: float
    order_tolerance: float

    @property
    def passes(self) -> bool:
        """True iff observed L2 order is within order_tolerance of formal order."""
        return abs(self.observed_order_l2 - self.formal_order) <= self.order_tolerance


def _l2_norm_periodic(err: NDArray[np.float64], dx: float) -> float:
    """Discrete L2 norm on a cell-centered periodic mesh: sqrt(sum(err^2) * dx)."""
    return float(np.sqrt(np.sum(err * err) * dx))


def _per_resolution_errors(
    rows: Sequence[PerResolutionResult],
) -> tuple[PerResolutionError, ...]:
    out: list[PerResolutionError] = []
    for row in rows:
        diff = row.u_numerical - row.u_exact
        out.append(
            PerResolutionError(
                N=row.N,
                dx=row.dx,
                l2_error=_l2_norm_periodic(diff, row.dx),
                linf_error=float(np.max(np.abs(diff))),
            )
        )
    return tuple(out)


def _fit_observed_order(dxs: NDArray[np.float64], errs: NDArray[np.float64]) -> float:
    """Least-squares fit of log(err) = p * log(dx) + c; return slope p.

    Filters out non-positive errors (which would yield -inf under log); if
    fewer than two valid points remain the fit raises `ValueError`.
    """
    mask = errs > 0.0
    if int(mask.sum()) < 2:
        raise ValueError("need at least two positive errors to fit an order")
    log_dx = np.log(dxs[mask])
    log_err = np.log(errs[mask])
    slope, _intercept = np.polyfit(log_dx, log_err, 1)
    return float(slope)


def analyze_convergence(
    result: RunnerResult,
    formal_order: float | None = None,
    order_tolerance: float = DEFAULT_ORDER_TOLERANCE,
) -> ConvergenceResult:
    """Compute per-resolution errors and fit an observed order."""
    formal = (
        formal_order if formal_order is not None else float(result.solution.formal_spatial_order)
    )
    rows = _per_resolution_errors(result.per_resolution)
    dxs = np.array([r.dx for r in rows], dtype=np.float64)
    l2 = np.array([r.l2_error for r in rows], dtype=np.float64)
    linf = np.array([r.linf_error for r in rows], dtype=np.float64)
    return ConvergenceResult(
        per_resolution=rows,
        formal_order=formal,
        observed_order_l2=_fit_observed_order(dxs, l2),
        observed_order_linf=_fit_observed_order(dxs, linf),
        order_tolerance=order_tolerance,
    )


def render_acceptance_markdown(
    result: RunnerResult,
    convergence: ConvergenceResult,
) -> str:
    """Render the acceptance report markdown (committed at `acceptance.md`)."""
    lines = [
        "# Heat-equation-1D MMS acceptance",
        "",
        "Generated by `tools/testkit/code_verification/mms/analyze.py`. The pipeline",
        "runs the reference solver at the listed resolutions, measures L2 and",
        "L-infinity errors against the manufactured solution, and fits the",
        "observed convergence order via least-squares in log-log space.",
        "",
        f"- Solver: `{result.solver_name}`",
        f"- Diffusivity D: {result.solution.D}",
        f"- Period L: {result.solution.L}",
        f"- CFL: {result.cfl}",
        f"- Final time: {result.t_final}",
        f"- Formal spatial order: {convergence.formal_order:.1f}",
        f"- Order tolerance: +/- {convergence.order_tolerance:.2f}",
        "",
        "## Per-resolution errors",
        "",
        "| N | dx | L2 error | L-inf error |",
        "|---|---|---|---|",
    ]
    for row in convergence.per_resolution:
        lines.append(f"| {row.N} | {row.dx:.6e} | {row.l2_error:.6e} | {row.linf_error:.6e} |")
    lines.extend(
        [
            "",
            "## Observed orders",
            "",
            f"- Observed order (L2): {convergence.observed_order_l2:.4f}",
            f"- Observed order (L-inf): {convergence.observed_order_linf:.4f}",
            "",
            (
                f"Verdict: **{'PASS' if convergence.passes else 'FAIL'}** -- "
                f"observed L2 order is within +/- {convergence.order_tolerance:.2f} "
                f"of formal order {convergence.formal_order:.1f}."
            ),
            "",
        ]
    )
    return "\n".join(lines)
