// Stack-B WebGPU driver for Growing Neural CA forward inference.
//
// Loads the converted checkpoint (flat-f32 buffer + layout sidecar from
// neural_ca/convert_checkpoint.py), wires the nca_inference.wgsl compute shader
// through `@bit-physics/common-ts`, rolls the NCA forward N steps from the
// seed, reads back the RGBA frame stack, and writes the canonical B-inference
// capture `growing-emoji-64sq-seed42-step1000-wgsl.{h5,json}`.
//
// Local-only — Phase-3 CI excludes WebGPU-device-requiring tests (spec § 7.8).
// The pure-NumPy oracle (neural_ca/reference/nca_numpy.py) is the CI-visible
// reproduction check. This file is the Phase-5 web-deploy path; in this
// environment the committed capture is generated by executing the SAME
// nca_inference.wgsl via the wgpu-py harness (no Node WebGPU runtime here).
//
// Stage 1a: scaffold. Stage 1b-B implements the driver.

import { createContext } from "../../../../common/common-ts/src/context.js";

export interface NCAInferenceParams {
  grid: number;
  channelN: number;
  steps: number;
  seed: number;
  fireRate: number;
}

export const CANONICAL_PARAMS: NCAInferenceParams = {
  grid: 64,
  channelN: 16,
  steps: 1000,
  seed: 42,
  fireRate: 0.5,
};

export const CANONICAL_DESCRIPTOR = "growing-emoji-64sq-seed42-step1000";

/**
 * Run the WGSL NCA forward inference and write the B-inference capture.
 * Stage 1b-B implements this.
 */
export async function runWgslInference(_params: NCAInferenceParams): Promise<void> {
  // TODO(Stage-1b-B): load converted weights, bind buffers via common-ts,
  // dispatch nca_inference.wgsl per step, read back RGBA, write capture.
  await createContext();
  throw new Error("neural-ca typescript runWgslInference — Stage 1b-B");
}
